import { DesignProject } from "./types";

export const DEFAULT_PROJECTS: DesignProject[] = [
  {
    id: "proj_card_tech",
    name: "AeroSpace Tech Solutions",
    productType: "Sampul Rapor",
    category: "Teknologi",
    concept: "Minimalis & Modern",
    audience: "B2B Clients, Investors",
    backgroundColor: "#0B1528",
    slogan: "Inovasi Tanpa Batas Space",
    description: "Desain berkonsep luar angkasa dengan nuansa teknologi tinggi, memadukan warna biru dongker dan aksen emas elektrik.",
    createdAt: "2026-06-21T09:12:00Z",
    status: "Final",
    palette: {
      primary: "#0B1528",
      secondary: "#1E3A8A",
      accent: "#10B981",
      explanation: "Biru gelap melambangkan kestabilan teknologi, dipadukan accent emerald untuk kesan segar dinamis."
    },
    typography: {
      title: "Space Grotesk",
      body: "Inter",
      explanation: "Font Space Grotesk yang futuristik berpadu kontras dengan kegunaan Inter yang bersih."
    },
    layoutType: "Creative",
    elements: [
      {
        id: "bg_rect_1",
        type: "shape",
        shapeType: "rectangle",
        x: 0,
        y: 85,
        width: 100,
        height: 15,
        color: "#1E3A8A",
        zIndex: 1
      },
      {
        id: "bg_rect_accent",
        type: "shape",
        shapeType: "rectangle",
        x: 0,
        y: 82,
        width: 100,
        height: 3,
        color: "#10B981",
        zIndex: 2
      },
      {
        id: "logo_sparkle",
        type: "logo",
        logoIcon: "sparkles",
        x: 8,
        y: 15,
        width: 8,
        height: 12,
        color: "#10B981",
        zIndex: 3
      },
      {
        id: "title_comp",
        type: "text",
        text: "AeroSpace Solutions",
        x: 18,
        y: 15,
        width: 70,
        height: 12,
        fontSize: 24,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        color: "#FFFFFF",
        align: "left",
        zIndex: 4
      },
      {
        id: "slogan_text",
        type: "text",
        text: "Inovasi Tanpa Batas Teknologi",
        x: 18,
        y: 28,
        width: 70,
        height: 6,
        fontSize: 12,
        fontFamily: "Inter",
        fontWeight: "normal",
        color: "#94A3B8",
        align: "left",
        zIndex: 5
      },
      {
        id: "name_person",
        type: "text",
        text: "Anam Jumantono",
        x: 8,
        y: 48,
        width: 80,
        height: 10,
        fontSize: 20,
        fontFamily: "Outfit",
        fontWeight: "bold",
        color: "#FFFFFF",
        align: "left",
        zIndex: 6
      },
      {
        id: "role_person",
        type: "text",
        text: "Chief Creative Officer & Founder",
        x: 8,
        y: 57,
        width: 80,
        height: 6,
        fontSize: 11,
        fontFamily: "Inter",
        fontWeight: "medium",
        color: "#10B981",
        align: "left",
        zIndex: 7
      },
      {
        id: "contact_address",
        type: "text",
        text: "✉ hello@aerospace.io  |  ☏ +62 812-3456-7890  |  🌐 aerospace.io",
        x: 8,
        y: 72,
        width: 84,
        height: 6,
        fontSize: 10,
        fontFamily: "Inter",
        fontWeight: "normal",
        color: "#CBD5E1",
        align: "left",
        zIndex: 8
      }
    ]
  },
  {
    id: "proj_rapor_klasik",
    name: "SMK Negeri 1 Yogyakarta",
    productType: "Sampul Rapor",
    category: "Pendidikan",
    concept: "Corporate & Formal",
    audience: "Siswa, Guru, Orang Tua",
    backgroundColor: "#115E59",
    slogan: "Cerdas Berkarakter Unggul",
    description: "Desain sampul rapor klasik bergaya kulit sintetis hijau toska tua (teal) berhias line bingkai emas khas sekolah negeri di Indonesia.",
    createdAt: "2026-06-22T04:30:00Z",
    status: "Draft",
    palette: {
      primary: "#115E59",
      secondary: "#0F766E",
      accent: "#F59E0B",
      explanation: "Teal tua memberi kewibawaan akademik formal, dipadu warna emas (Amber) mencerminkan prestasi emas siswa."
    },
    typography: {
      title: "Playfair Display",
      body: "Inter",
      explanation: "Kombinasi klasik Serif megah untuk nama institusi berpadu Sans-serif rapi untuk identitas personal."
    },
    layoutType: "Corporate",
    elements: [
      {
        id: "border_frame_outer",
        type: "shape",
        shapeType: "rectangle",
        x: 4,
        y: 3,
        width: 92,
        height: 94,
        color: "#F59E0B",
        zIndex: 1
      },
      {
        id: "border_frame_inner",
        type: "shape",
        shapeType: "rectangle",
        x: 5,
        y: 4,
        width: 90,
        height: 92,
        color: "#115E59",
        zIndex: 2
      },
      {
        id: "logo_school",
        type: "logo",
        logoIcon: "mortarboard",
        x: 44,
        y: 12,
        width: 12,
        height: 10,
        color: "#F59E0B",
        zIndex: 3
      },
      {
        id: "school_header_1",
        type: "text",
        text: "LAPORAN HASIL BELAJAR",
        x: 10,
        y: 25,
        width: 80,
        height: 6,
        fontSize: 22,
        fontFamily: "Space Grotesk",
        fontWeight: "bold",
        color: "#F59E0B",
        align: "center",
        zIndex: 4
      },
      {
        id: "school_header_2",
        type: "text",
        text: "SMK NEGERI 1 YOGYAKARTA",
        x: 10,
        y: 31,
        width: 80,
        height: 5,
        fontSize: 18,
        fontFamily: "Playfair Display",
        fontWeight: "bold",
        color: "#FFFFFF",
        align: "center",
        zIndex: 5
      },
      {
        id: "decor_line",
        type: "shape",
        shapeType: "line",
        x: 35,
        y: 38,
        width: 30,
        height: 2,
        color: "#F59E0B",
        zIndex: 6
      },
      {
        id: "id_box_outer",
        type: "shape",
        shapeType: "rectangle",
        x: 15,
        y: 48,
        width: 70,
        height: 32,
        color: "#0F766E",
        zIndex: 7
      },
      {
        id: "identitas_siswa_title",
        type: "text",
        text: "IDENTITAS PESERTA DIDIK",
        x: 20,
        y: 52,
        width: 60,
        height: 4,
        fontSize: 14,
        fontFamily: "Inter",
        fontWeight: "bold",
        color: "#F59E0B",
        align: "center",
        zIndex: 8
      },
      {
        id: "student_name",
        type: "text",
        text: "NAMA : AMELIA CHANDRA",
        x: 22,
        y: 60,
        width: 56,
        height: 4,
        fontSize: 13,
        fontFamily: "Inter",
        fontWeight: "medium",
        color: "#FFFFFF",
        align: "left",
        zIndex: 9
      },
      {
        id: "student_nisn",
        type: "text",
        text: "NISN : 0081249912",
        x: 22,
        y: 66,
        width: 56,
        height: 4,
        fontSize: 13,
        fontFamily: "Inter",
        fontWeight: "medium",
        color: "#FFFFFF",
        align: "left",
        zIndex: 10
      },
      {
        id: "student_class",
        type: "text",
        text: "KELAS : XI REKAYASA PERANGKAT LUNAK",
        x: 22,
        y: 72,
        width: 56,
        height: 4,
        fontSize: 13,
        fontFamily: "Inter",
        fontWeight: "medium",
        color: "#FFFFFF",
        align: "left",
        zIndex: 11
      },
      {
        id: "footer_year",
        type: "text",
        text: "TAHUN AJARAN 2026/2027",
        x: 10,
        y: 86,
        width: 80,
        height: 4,
        fontSize: 12,
        fontFamily: "Inter",
        fontWeight: "normal",
        color: "#CBD5E1",
        align: "center",
        zIndex: 12
      }
    ]
  },
  {
    id: "proj_card_minimalist",
    name: "Minimalist Studio",
    productType: "Sampul Rapor",
    category: "Creative Services",
    concept: "Minimalist",
    audience: "Creative Directors, Art Curators",
    backgroundColor: "#FDFCFA",
    slogan: "Sederhana Itu Indah",
    description: "Desain ultra-minimalis dengan latar krem pudar, memadukan font Playfair Display yang berkelas dengan penempatan logo asimetris elegan.",
    createdAt: "2026-06-22T08:00:00Z",
    status: "Draft",
    palette: {
      primary: "#FDFCFA",
      secondary: "#1A1A1A",
      accent: "#D97706",
      explanation: "Warna off-white hangat dipadukan charcoal dan aksen amber melambangkan kemurnian ide seni."
    },
    typography: {
      title: "Playfair Display",
      body: "Inter",
      explanation: "Title serif klasik romantis berpadu dengan keanggunan layout modern."
    },
    layoutType: "Minimalist",
    elements: [
      {
        id: "card_logo",
        type: "logo",
        logoIcon: "shield",
        x: 10,
        y: 20,
        width: 8,
        height: 12,
        color: "#1A1A1A",
        zIndex: 1
      },
      {
        id: "studio_title",
        type: "text",
        text: "THE CREATIVE ATELIER",
        x: 22,
        y: 20,
        width: 60,
        height: 10,
        fontSize: 22,
        fontFamily: "Playfair Display",
        fontWeight: "bold",
        color: "#1A1A1A",
        align: "left",
        zIndex: 2
      },
      {
        id: "studio_body",
        type: "text",
        text: "Bespoke Art & Identity Curation",
        x: 22,
        y: 33,
        width: 60,
        height: 5,
        fontSize: 11,
        fontFamily: "Inter",
        fontWeight: "normal",
        color: "#78716C",
        align: "left",
        zIndex: 3
      },
      {
        id: "line_sep",
        type: "shape",
        shapeType: "line",
        x: 10,
        y: 44,
        width: 50,
        height: 1,
        color: "#D97706",
        zIndex: 4
      },
      {
        id: "pic_card_name",
        type: "text",
        text: "DIAN SASTRO",
        x: 10,
        y: 52,
        width: 80,
        height: 8,
        fontSize: 16,
        fontFamily: "Outfit",
        fontWeight: "bold",
        color: "#1A1A1A",
        align: "left",
        zIndex: 5
      },
      {
        id: "pic_card_job",
        type: "text",
        text: "Artistic Director & Head Curator",
        x: 10,
        y: 60,
        width: 80,
        height: 5,
        fontSize: 11,
        fontFamily: "Inter",
        fontWeight: "medium",
        color: "#D97706",
        align: "left",
        zIndex: 6
      },
      {
        id: "pic_card_social",
        type: "text",
        text: "instagram.com/thecreative | diansastro@artelier.com | Jakarta",
        x: 10,
        y: 75,
        width: 80,
        height: 5,
        fontSize: 9,
        fontFamily: "Inter",
        fontWeight: "normal",
        color: "#78716C",
        align: "left",
        zIndex: 7
      }
    ]
  }
];
